name: Build and Push Web Dev Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Grava Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.EXTERNAL_PRIVATE_REGISTRY }}
          username: ${{ secrets.EXTERNAL_PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.EXTERNAL_PRIVATE_REGISTRY_PASSWORD }}

      - name: Set API URL for development
        id: set-api-url
        run: |
          echo "api_url=https://api.telescope.dev.grava.io" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: docker/Dockerfile
          build-args: |
            REACT_APP_API_URL=${{ steps.set-api-url.outputs.api_url }}
            REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          tags: ${{ secrets.EXTERNAL_PRIVATE_REGISTRY }}/telescope/web:${{ github.ref_name }}
